### ISSUE TITLE
msg's color invalid after import process bar package tqdm

### ISSUE THREAD

**Issue by Holy-Shine** [explosion/wasabi#19]
Hello,
When I use `wasabi` and process bar package `tqdm`  together, wasabi Printer's color will be invalid. Just like this:
![image](https://user-images.githubusercontent.com/14997709/154431847-b1031487-c886-4919-ad80-4fe5a6898bc0.png)
code result:
![image](https://user-images.githubusercontent.com/14997709/154431896-13c74411-8870-4e15-9ea8-a7b4f95341db.png)

How could it be like this？

**Comment by njsmith** [comment]
I'm guessing you're on Windows? There's a bug in the lower-level library `colorama` where in some circumstances it can breaks ANSI support on Windows for your whole program, and tqdm uses colorama. There's a PR upstream to fix it: https://github.com/tqdm/tqdm/pull/1394

I don't think there's anything we can do about this in wasabi though, since the problem is in tqdm, and possibly any other libraries you have installed that are calling the old `colorama.init` function.
